name: Build NephroPath for macOS

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify a stable version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name=NephroPath_mac --icon=NephroPath_installer_icon.ico CKD_auto_mac.py

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath-macOS
          path: dist/NephroPath_mac
