name: Build NephroPath for macOS
on: [push]
jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify a stable version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name=NephroPath_mac --icon=NephroPath_installer_icon.icns CKD_auto_mac.py

      - name: Move release
        run: |
          mv dist/NephroPath_mac ./NephroPath_mac
      
      - name: Test NephroPath_mac
        run: |
          chmod +x ./NephroPath_mac
          ./NephroPath_mac  # Simply execute the file
          
      - name: Set up Git
        run: |
          git config --global user.email "nicholas.killough@outlook.com"
          git config --global user.name "NKillough32"
          git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/NKillough32/CKD-Review.git
          git fetch origin

      - name: Commit and push changes
        run: |
          git checkout main
          git pull origin main
          git add NephroPath_mac
          git commit -m "Add built NephroPath_mac"
          git push origin main

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath-macOS
          path: NephroPath_mac
