name: Build NephroPath for Windows and macOS

on:
  push:
    branches: [main]
    paths-ignore:
      - 'Alternative_versions/**'
      - 'NephroPath.exe'
      - 'NephroPath_html.exe'
      - 'NephroPath_mac'
      - 'NephroPath_mac_html'

# Prevent multiple simultaneous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - name: NephroPath
            script: Code/CKD_Master_pdf2.py
            output: NephroPath.exe
          - name: NephroPath_html
            script: Code/CKD_Master_html.py
            output: NephroPath_html.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'Dependencies/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install pyinstaller

      - name: Verify required files exist
        shell: pwsh
        run: |
          $requiredFiles = @(
            "EMIS_Files/Creatinine.csv",
            "EMIS_Files/CKD_check.csv",
            "Dependencies/contraindicated_drugs.csv",
            "Dependencies/drug_adjustment.csv",
            "Dependencies/statins.csv",
            "Dependencies/NephroPath_installer_icon.ico"
          )
          foreach ($file in $requiredFiles) {
            if (-Not (Test-Path $file)) {
              Write-Error "Missing required file: $file"
              exit 1
            } else {
              Write-Host "Found: $file"
            }
          }

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name=${{ matrix.name }} --icon=Dependencies/NephroPath_installer_icon.ico --log-level DEBUG ${{ matrix.script }}

      - name: Move release
        run: |
          New-Item -ItemType Directory -Force -Path .\Alternative_versions
          Move-Item dist\${{ matrix.output }} .\Alternative_versions\${{ matrix.output }} -Force
  
      - name: Test ${{ matrix.output }}
        shell: pwsh
        run: |
            .\Alternative_versions\${{ matrix.output }}
            if ($LASTEXITCODE -ne 0) {
              Write-Error "Test run of ${{ matrix.output }} failed with exit code $LASTEXITCODE"
              exit 1
            }
            Write-Host "${{ matrix.output }} ran successfully"
  
      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -f Alternative_versions/${{ matrix.output }}
          git commit -m "Update built ${{ matrix.output }}" || echo "No changes to commit"
          git stash
          git fetch origin main
          git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, aborting" && exit 1)
          git stash pop || echo "No changes to apply"
          git push origin main

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-Windows
          path: Alternative_versions/${{ matrix.output }}

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - name: NephroPath_mac
            script: Code/CKD_Master_pdf2.py
            output: NephroPath_mac
          - name: NephroPath_mac_html
            script: Code/CKD_Master_html.py
            output: NephroPath_mac_html
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'Dependencies/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install pyinstaller

      - name: Verify required files exist
        run: |
          required_files=(
            "EMIS_Files/Creatinine.csv"
            "EMIS_Files/CKD_check.csv"
            "Dependencies/contraindicated_drugs.csv"
            "Dependencies/drug_adjustment.csv"
            "Dependencies/statins.csv"
            "Dependencies/NephroPath_installer_icon.icns"
          )
          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "Error: Missing required file: $file" >&2
              exit 1
            else
              echo "Found: $file"
            fi
          done

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name=${{ matrix.name }} --icon=Dependencies/NephroPath_installer_icon.icns --log-level DEBUG ${{ matrix.script }}

      - name: Move release
        run: |
          mkdir -p ./Alternative_versions
          mv dist/${{ matrix.output }} ./Alternative_versions/${{ matrix.output }}

      - name: Test ${{ matrix.output }}
        run: |
          ./Alternative_versions/${{ matrix.output }}
          if [ $? -ne 0 ]; then
            echo "Error: Test run of ${{ matrix.output }} failed" >&2
            exit 1
          fi
          echo "${{ matrix.output }} ran successfully"

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -f Alternative_versions/${{ matrix.output }}
          git commit -m "Update built ${{ matrix.output }}" || echo "No changes to commit"
          git stash
          git fetch origin main
          git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, aborting" && exit 1)
          git stash pop || echo "No changes to apply"
          git push origin main

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-macOS
          path: Alternative_versions/${{ matrix.output }}