name: Build NephroPath PDF for Windows and macOS

on:
  push:
    branches: [main]
    paths-ignore:
      - 'NephroPath.exe'
      - 'NephroPath_mac'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'Dependencies/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install reportlab pyinstaller qrcode

      - name: Verify required files exist
        shell: cmd
        run: |
          if not exist "Code\CKD_core.py" (
            echo "CKD_core.py not found!"
            exit 1
          )
          if not exist "Dependencies\version_info.txt" (
            echo "version_info.txt not found!"
            exit 1
          )
          echo "All required files found."

      - name: Build with PyInstaller (Windows)
        run: |
          python -m PyInstaller --onefile 
          --name=NephroPath 
          --icon=Dependencies/NephroPath_installer_icon.ico 
          --version-file=Dependencies/version_info.txt `
          --add-data "Code/CKD_core.py;." 
          --add-data "Code/CKD_pdf_files_new.py;." 
          --hidden-import CKD_pdf_files_new 
          Code/CKD_Master_pdf_exefree.py

      - name: Move release
        run: |
          if (-not (Test-Path "dist\NephroPath.exe")) {
            Write-Error "dist\NephroPath.exe not found. PyInstaller build may have failed."
            exit 1
          }
          Move-Item dist\NephroPath.exe .\NephroPath.exe -Force

      - name: Test NephroPath.exe
        shell: pwsh
        run: |
          .\NephroPath.exe
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Test run of NephroPath.exe failed with exit code $LASTEXITCODE"
            exit 1
          }
          Write-Host "NephroPath.exe ran successfully"

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -f NephroPath.exe
          git commit -m "Update built NephroPath.exe" || echo "No changes to commit"
          git fetch origin main
          git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, aborting" && exit 1)
          git push origin main

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath-Windows
          path: NephroPath.exe

  build-macos:
    runs-on: macos-latest
    needs: build-windows  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'Dependencies/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install reportlab pyinstaller qrcode

      - name: Verify CKD_core.py exists
        run: |
          if [ ! -f "Code/CKD_core.py" ]; then
            echo "CKD_core.py not found!"
            exit 1
          else
            echo "CKD_core.py found."
          fi

      - name: Build with PyInstaller (macOS)
        run: |
          python -m PyInstaller --onefile --name=NephroPath_mac --add-data "Code/CKD_core.py:." --add-data "Code/CKD_pdf_files_new.py:." --hidden-import CKD_pdf_files_new Code/CKD_Master_pdf_exefree.py

      - name: Move release
        run: |
          if [ ! -f "dist/NephroPath_mac" ]; then
            echo "Error: dist/NephroPath_mac not found. PyInstaller build may have failed." >&2
            exit 1
          fi
          mv dist/NephroPath_mac ./NephroPath_mac

      - name: Test NephroPath_mac
        run: |
          ./NephroPath_mac
          if [ $? -ne 0 ]; then
            echo "Error: Test run of NephroPath_mac failed" >&2
            exit 1
          fi
          echo "NephroPath_mac ran successfully"

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -f NephroPath_mac
          git commit -m "Update built NephroPath_mac" || echo "No changes to commit"
          git fetch origin main
          git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, aborting" && exit 1)
          git push origin main

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath_mac-macOS
          path: NephroPath_mac