name: Build NephroPath PDF for Windows and macOS

on:
  push:
    branches: [main]
    paths-ignore:
      - 'NephroPath_win_pdf.exe'
      - 'NephroPath_mac_pdf'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install reportlab pyinstaller qrcode

      - name: Build with PyInstaller (Windows)
        run: |
          python -m PyInstaller --onefile --name=NephroPath_win_pdf --icon=Dependencies/NephroPath_installer_icon.ico --add-data "Code/CKD_core.py;." --add-data "Code/CKD_pdf_files_new.py;." --add-data "Dependencies;Dependencies" --add-data "EMIS_Files;EMIS_Files" Code/CKD_Master_pdf_exefree.py

      - name: Move release
        run: |
          Move-Item dist\NephroPath_win_pdf.exe .\NephroPath_win_pdf.exe -Force

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -f NephroPath_win_pdf.exe
          git commit -m "Update built NephroPath_win_pdf.exe" || echo "No changes to commit"
          git push origin main

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath_win_pdf-Windows
          path: NephroPath_win_pdf.exe