name: Build NephroPath for Windows and macOS

on:
  push:
    branches: [main]
    paths-ignore:
      - 'NephroPath.exe'
      - 'NephroPath_html.exe'
      - 'NephroPath_mac'
      - 'NephroPath_mac_html'

# Prevent multiple simultaneous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - name: NephroPath
            script: Code/CDK_Master_pdf.py
            output: NephroPath.exe
          - name: NephroPath_html
            script: Code/CDK_Master_html.py
            output: NephroPath_html.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name=${{ matrix.name }} --icon=Dependencies/NephroPath_installer_icon.ico ${{ matrix.script }}

      - name: Move release
        run: |
          Move-Item dist\${{ matrix.output }} .\${{ matrix.output }} -Force

      - name: Test ${{ matrix.output }}
        shell: pwsh
        run: |
          .\${{ matrix.output }}
          if (!$?) { exit 1 }

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          # Stage and commit unstaged changes
          git add -f ${{ matrix.output }}
          git commit -m "Update built ${{ matrix.output }}" || echo "No changes to commit"
          # Fetch latest changes and rebase
          git fetch origin main
          git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, aborting" && exit 1)
          # Push changes to remote repository
          git push origin main

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-Windows
          path: ${{ matrix.output }}

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - name: NephroPath_mac
            script: Code/CDK_Master_pdf.py
            output: NephroPath_mac
          - name: NephroPath_mac_html
            script: Code/CDK_Master_html.py
            output: NephroPath_mac_html
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name=${{ matrix.name }} --icon=Dependencies/NephroPath_installer_icon.icns ${{ matrix.script }}

      - name: Move release
        run: |
          mv dist/${{ matrix.output }} ./${{ matrix.output }}

      - name: Test ${{ matrix.output }}
        run: |
          ./${{ matrix.output }}
          if [ $? -ne 0 ]; then exit 1; fi

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          # Stage and commit unstaged changes
          git add -f ${{ matrix.output }}
          git commit -m "Update built ${{ matrix.output }}" || echo "No changes to commit"
          # Fetch latest changes and rebase
          git fetch origin main
          git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, aborting" && exit 1)
          # Push changes to remote repository
          git push origin main

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-macOS
          path: ${{ matrix.output }}