name: Build NephroPath PDF for Windows and macOS

on:
  push:
    branches: [main]
    paths-ignore:
      - 'NephroPath_win_pdf.exe'
      - 'NephroPath_mac_pdf'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'Dependencies/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install reportlab pyinstaller qrcode

      - name: Debug directory structure
        shell: cmd
        run: |
          dir
          dir Code

      - name: Verify CKD_core.py exists
        shell: cmd
        run: |
          if not exist "Code\CKD_core.py" (
            echo "CKD_core.py not found!"
            exit 1
          ) else (
            echo "CKD_core.py found."
          )

      - name: Build with PyInstaller (Windows)
        run: |
          python -m PyInstaller --onefile --name=NephroPath_win_pdf --icon=Dependencies/NephroPath_installer_icon.ico --add-data "Code/CKD_core.py;." --add-data "Code/CKD_pdf_files_new.py;." --add-data "Dependencies;Dependencies" --hidden-import CKD_pdf_files_new --log-level DEBUG Code/CKD_Master_pdf_exefree.py

      - name: Debug dist directory
        shell: cmd
        run: |
          dir dist

      - name: Move release
        run: |
          if (-not (Test-Path "dist\NephroPath_win_pdf.exe")) {
            Write-Error "dist\NephroPath_win_pdf.exe not found. PyInstaller build may have failed."
            exit 1
          }
          Move-Item dist\NephroPath_win_pdf.exe .\NephroPath_win_pdf.exe -Force

      - name: Test NephroPath_win_pdf.exe
        shell: pwsh
        run: |
          .\NephroPath_win_pdf.exe
          if ($LASTEXITCODE -ne 0) {
            Write-Error "Test run of NephroPath_win_pdf.exe failed with exit code $LASTEXITCODE"
            exit 1
          }
          Write-Host "NephroPath_win_pdf.exe ran successfully"

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -f NephroPath_win_pdf.exe
          git commit -m "Update built NephroPath_win_pdf.exe" || echo "No changes to commit"
          git fetch origin main
          git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, aborting" && exit 1)
          git push origin main

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath_win_pdf-Windows
          path: NephroPath_win_pdf.exe

  build-macos:
    runs-on: macos-latest
    needs: build-windows  # Ensure this job runs after build-windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'Dependencies/requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install reportlab pyinstaller qrcode

      - name: Debug directory structure
        run: |
          ls -R

      - name: Verify CKD_core.py exists
        run: |
          if [ ! -f "Code/CKD_core.py" ]; then
            echo "CKD_core.py not found!"
            exit 1
          else
            echo "CKD_core.py found."
          fi

      - name: Build with PyInstaller (macOS)
        run: |
          python -m PyInstaller --onefile --name=NephroPath_mac_pdf --add-data "Code/CKD_core.py:." --add-data "Code/CKD_pdf_files_new.py:." --add-data "Dependencies:Dependencies" --hidden-import CKD_pdf_files_new --log-level DEBUG Code/CKD_Master_pdf_exefree.py

      - name: Debug dist directory
        run: |
          ls -R dist

      - name: Move release
        run: |
          if [ ! -f "dist/NephroPath_mac_pdf" ]; then
            echo "Error: dist/NephroPath_mac_pdf not found. PyInstaller build may have failed." >&2
            exit 1
          fi
          mv dist/NephroPath_mac_pdf ./NephroPath_mac_pdf

      - name: Test NephroPath_mac_pdf
        run: |
          ./NephroPath_mac_pdf
          if [ $? -ne 0 ]; then
            echo "Error: Test run of NephroPath_mac_pdf failed" >&2
            exit 1
          fi
          echo "NephroPath_mac_pdf ran successfully"

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add -f NephroPath_mac_pdf
          git commit -m "Update built NephroPath_mac_pdf" || echo "No changes to commit"
          git fetch origin main
          git pull --rebase origin main || (git rebase --abort && echo "Rebase failed, aborting" && exit 1)
          git push origin main

      - name: Upload macOS executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath_mac_pdf-macOS
          path: NephroPath_mac_pdf