name: Build NephroPath for Windows without pdf

on:
  push:
    branches: [main]
    paths-ignore:
      - 'NephroPath_nopdf.exe'

permissions:
  contents: write  # Allow write access for the GITHUB_TOKEN

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name=NephroPath_nopdf --icon=NephroPath_installer_icon.ico CKD_auto_nopdf.py

      - name: Move release
        run: |
          Move-Item dist\NephroPath_nopdf.exe .\NephroPath_nopdf.exe -Force

      - name: Test NephroPath_nopdf.exe
        shell: pwsh
        run: |
          .\NephroPath_nopdf.exe
          if (!$?) { exit 1 }

      - name: Commit and push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git config pull.rebase false
          git pull origin main
          git add -f NephroPath_nopdf.exe
          git commit -m "Add built NephroPath_nopdf.exe" || echo "No changes to commit"
          git push origin main

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath-Windows_nopdf
          path: NephroPath_nopdf.exe
