name: Build NephroPath for Windows

on:
  push:
    branches: [main]
    paths-ignore:
      - 'NephroPath.exe'

# Prevent multiple simultaneous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Dependencies/requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name=NephroPath --icon=Dependencies/NephroPath_installer_icon.ico Code/CKD_auto.py

      - name: Move release
        run: |
          Move-Item dist\NephroPath.exe .\NephroPath.exe -Force

      - name: Test NephroPath.exe
        shell: pwsh
        run: |
          .\NephroPath.exe
          if (!$?) { exit 1 }

      - name: Commit and push changes  
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          # Stage and commit unstaged changes
          git add -f NephroPath.exe
          git commit -m "Update built NephroPath.exe" || echo "No changes to commit"
          # Fetch latest changes and rebase
          git fetch origin main
          git rebase origin/main
          # Push changes to remote repository
          git push origin main

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath-Windows
          path: NephroPath.exe