name: Build NephroPath for Windows

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Specify a stable version for consistency

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --onefile --name=NephroPath --icon=NephroPath_installer_icon.ico CKD_auto.py

      - name: Move release
        run: |
          Move-Item dist\NephroPath.exe .\NephroPath.exe -Force

      - name: Test NephroPath.exe
        shell: pwsh  # Use PowerShell for scripting
        run: |
          .\NephroPath.exe  # Execute the file
          if (!$?) { exit 1 }  # Exit with error if the executable fails
          
      - name: Set up Git
        run: |
          git config --global user.email "nicholas.killough@outlook.com"
          git config --global user.name "NKillough32"
          git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/NKillough32/CKD-Review.git
          git fetch origin

      - name: Commit and push changes
        run: |
          git checkout main
          git pull origin main
          git add NephroPath.exe
          git commit -m "Add built NephroPath.exe"
          git push origin main

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: NephroPath-Windows
          path: NephroPath.exe
